library(tidyverse)
library(shiny)
library(shinythemes)
library(rsconnect)

pc <- read.csv("pc.csv")
int <- read.csv("int.csv")
tic <- read.csv("tic.csv")

ui <- fluidPage(theme = shinytheme("yeti"),
                title = "Acceso TIC",
                titlePanel(title = h1(strong("Acceso a las Tecnologías de Información y Computación 
                                             en Argentina"), style="text-align: center")),
                tabsetPanel(type = "tabs",
                            tabPanel("Acceso a PC - Estudiantes", fluid = TRUE,
                                     titlePanel(title = h1("Acceso a computadoras según región geográfica y gestión educativa - Estudiantes de nivel primario y secundario", style="text-align: center")),
                                     br(),
                                     br(),
                                     sidebarPanel(
                                       selectInput(inputId = "pc_region", 
                                                   label = strong("Región"),
                                                   choices = unique(pc$Region),
                                                   selected = "AMBA"),
                                       selectInput(inputId = "pc_gestion", 
                                                   label = strong("Gestión"),
                                                   choices = unique(pc$sector_esc),
                                                   selected = "Estatal"),
                                       selectInput(inputId = "pc_nivel", 
                                                   label = strong("Nivel"),
                                                   choices = unique(pc$nivel_en_curso),
                                                   selected = "Primaria")),
                                     mainPanel(plotOutput(outputId = "pc_bars", height = 500)),
                                     br(),
                                     br(),
                                     tabPanel("ENCP",
                                              p(HTML("<b>Unidad de análisis:</b> Cada niño/a o adolescente miembro de los hogares relevados que estuviera cursando el nivel primario o secundario.")),
                                              p(HTML("<b>Fuente:</b>   Elaboración propia en base a datos de Encuesta a Hogares - Evaluación Nacional del proceso de la 
                                Continuidad Pedagógica (SEIE-ME/ UNICEF). Junio 2020."))),
                                     br(),
                                     br(),
                                     tabPanel("Acceso a comptadoras", fluid = TRUE,
                                              titlePanel(title = h1("Acceso a computadoras - Estudiantes de nivel primario y secundario - Total país", style="text-align: center")),
                                              HTML('<center><img src="pc.jpeg"></center>')),
                                     br(),
                                     tabPanel("ENCP",
                                              p(HTML("<b>Unidad de análisis:</b> Cada niño/a o adolescente miembro de los hogares relevados que estuviera cursando el nivel primario o secundario.")),
                                              p(HTML("<b>Fuente:</b>   Elaboración propia en base a datos de Encuesta a Hogares - Evaluación Nacional del proceso de la 
                                Continuidad Pedagógica (SEIE-ME/ UNICEF). Junio 2020.")))),
                            tabPanel("Acceso a internet - Estudiantes", fluid= TRUE,
                                     titlePanel(title = h1("Acceso a internet según región geográfica y gestión educativa - Estudiantes de nivel primario y secundario", style="text-align: center")),
                                     br(),
                                     br(),
                                     sidebarPanel(
                                       selectInput(inputId = "int_region", 
                                                   label = strong("Región"),
                                                   choices = unique(int$Region),
                                                   selected = "AMBA"),
                                       selectInput(inputId = "int_gestion", 
                                                   label = strong("Gestión"),
                                                   choices = unique(int$sector_esc),
                                                   selected = "Estatal"),
                                       selectInput(inputId = "int_nivel", 
                                                   label = strong("Nivel"),
                                                   choices = unique(int$nivel_en_curso),
                                                   selected = "Primaria")),
                                     mainPanel(plotOutput(outputId = "int_bars", height = 500)),
                                     br(),
                                     br(),
                                     tabPanel("ENCP",
                                              p(HTML("<b>Unidad de análisis:</b> Cada niño/a o adolescente miembro de los hogares relevados que estuviera cursando el nivel primario o secundario.")),
                                              p(HTML("<b>Fuente:</b>   Elaboración propia en base a datos de Encuesta a Hogares - Evaluación Nacional del proceso de la 
                                Continuidad Pedagógica (SEIE-ME/ UNICEF). Junio 2020."))),
                                     br(),
                                     br(),
                                     titlePanel(title = h1("Acceso a internet -  Estudiantes de nivel primario y secundario - Total país", style="text-align: center")),
                                     HTML('<center><img src="internet.jpeg"></center>'),
                                     br(),
                                     tabPanel("ENCP",
                                              p(HTML("<b>Unidad de análisis:</b> Cada niño/a o adolescente miembro de los hogares relevados que estuviera cursando el nivel primario o secundario.")),
                                              p(HTML("<b>Fuente:</b>   Elaboración propia en base a datos de Encuesta a Hogares - Evaluación Nacional del proceso de la 
                                Continuidad Pedagógica (SEIE-ME/ UNICEF). Junio 2020.")))),
                            tabPanel("Acceso a PC e internet - Estudiantes", fluid = TRUE,
                                     titlePanel(title = h1("Acceso a computadoras e internet según región geográfica y gestión educativa - Estudiantes de nivel primario y secundario", style="text-align: center")),
                                     br(),
                                     br(),
                                     sidebarPanel(
                                       selectInput(inputId = "tic_region", 
                                                   label = strong("Región"),
                                                   choices = unique(tic$Region),
                                                   selected = "AMBA"),
                                       selectInput(inputId = "tic_gestion", 
                                                   label = strong("Gestión"),
                                                   choices = unique(tic$sector_esc),
                                                   selected = "Estatal"),
                                       selectInput(inputId = "tic_nivel", 
                                                   label = strong("Nivel"),
                                                   choices = unique(tic$nivel_en_curso),
                                                   selected = "Primaria")),
                                     mainPanel(plotOutput(outputId = "tic_bars", height = 500)),
                                     br(),
                                     br(),
                                     tabPanel("ENCP",
                                              p(HTML("<b>Unidad de análisis:</b> Cada niño/a o adolescente miembro de los hogares relevados que estuviera cursando el nivel primario o secundario.")),
                                              p(HTML("<b>Fuente:</b>   Elaboración propia en base a datos de Encuesta a Hogares - Evaluación Nacional del proceso de la 
                                Continuidad Pedagógica (SEIE-ME/ UNICEF). Junio 2020."))),
                                     br(),
                                     br(),
                                     titlePanel(title = h1("Acceso a computadoras e internet - Estudiantes de nivel primario y secundario - Total país", style="text-align: center")),
                                     HTML('<center><img src="tic.jpeg"></center>'),
                                     br(),
                                     tabPanel("ENCP",
                                              p(HTML("<b>Unidad de análisis:</b> Cada niño/a o adolescente miembro de los hogares relevados que estuviera cursando el nivel primario o secundario.")),
                                              p(HTML("<b>Fuente:</b>   Elaboración propia en base a datos de Encuesta a Hogares - Evaluación Nacional del proceso de la 
                                Continuidad Pedagógica (SEIE-ME/ UNICEF). Junio 2020.")))),
                            tabPanel("Acceso a internet - Población general", fluid = TRUE,
                                     titlePanel(title = h1("Acceso fijo a internet cada 100 habitantes según provincia - Población general", style="text-align: center")),
                                     br(),
                                     HTML('<center><img src="int_prov.jpg"></center>'),
                                     tabPanel("ENACOM",
                                              p(HTML("<b>Fuente:</b> Elaboración propia en base a datos de ENACOM - 2021."))),
                                     br(),
                                     br(),
                                     titlePanel(title = h1("Evolución del acceso fijo a internet cada 100 habitantes - Población general - Total país", style="text-align: center")),
                                     br(),
                                     HTML('<center><img src="int_evol.jpg"></center>'),
                                     tabPanel("ENACOM",
                                              p(HTML("<b>Fuente:</b> Elaboración propia en base a datos de ENACOM - 2021."))))))